import { test, expect } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

// Define the screenshot paths (save in the current conversation's brain folder)
const CONV_ID = "60559471-6cc6-403e-8b83-142c0615aa66";
const SCREENSHOT_DIR = `C:/Users/Garret/.gemini/antigravity/brain/${CONV_ID}`;

// Create directory if it doesn't exist
if (!fs.existsSync(SCREENSHOT_DIR)) {
  fs.mkdirSync(SCREENSHOT_DIR, { recursive: true });
}

test('Run E2E UX Simulation for Alice Chen', async ({ page }) => {
  page.on('console', msg => console.log('PAGE CONSOLE:', msg.text()));
  page.on('pageerror', err => console.log('PAGE ERROR:', err.message));

  // Load session tokens generated by wallet-factory
  const tokensPath = path.join(process.cwd(), 'session_tokens.json');
  if (!fs.existsSync(tokensPath)) {
    throw new Error(`session_tokens.json not found at ${tokensPath}. Run wallet-factory first.`);
  }
  const tokens = JSON.parse(fs.readFileSync(tokensPath, 'utf-8'));
  
  const creator = tokens.CREATOR;
  const worker = tokens.WORKER;

  console.log('--- Step 1: Navigate to Marketplace Dashboard ---');
  await page.goto('http://localhost:3000/');
  await page.waitForTimeout(1000); // Wait for transitions
  await page.screenshot({ path: `${SCREENSHOT_DIR}/marketplace_dashboard_1784331313386.png` });

  console.log('--- Step 2: Open Wallet Connection Modal ---');
  await page.locator('#wallet-connect-btn').click();
  await page.waitForTimeout(500); // Wait for dropdown animation
  await page.screenshot({ path: `${SCREENSHOT_DIR}/wallet_connection_modal_1784331321645.png` });

  // Close dropdown by clicking header or blank space
  await page.mouse.click(10, 10);
  await page.waitForTimeout(300);

  console.log('--- Step 3: Authenticate as Creator (Alice Chen) & Complete Form ---');
  // Inject Creator credentials into localStorage
  await page.evaluate((creds) => {
    window.localStorage.setItem('algobounty_jwt', creds.jwt);
    window.localStorage.setItem('algobounty_address', creds.address);
    window.localStorage.setItem('algobounty_connected', 'true');
    window.localStorage.setItem('algobounty_wallet_type', 'pera');
  }, { jwt: creator.jwt, address: creator.address });

  // Navigate to create page with credentials injected
  await page.goto('http://localhost:3000/create');
  await page.waitForSelector('#description');

  // Fill in form fields
  await page.fill('#description', 'Build a Next.js Landing Page for AlgoBounty');
  await page.fill('#amount', '150');
  await page.fill('#karma', '10');
  await page.fill('#repo-url', 'https://github.com/IcanBENCHurCAT/algo-bounty');
  await page.fill('#repo-labels', 'bug, ui');
  await page.fill('#tags', 'nextjs, wallet, typescript');
  
  // Toggle HITM mode
  await page.locator('#hitm-toggle').click();
  await page.waitForSelector('#hitm-days');
  await page.fill('#hitm-days', '7');

  // Check the mandatory tax disclaimer checkbox
  await page.locator('#tax-disclaimer-checkbox').check();

  await page.waitForTimeout(1000); // Allow values to settle
  await page.screenshot({ path: `${SCREENSHOT_DIR}/create_bounty_form_1784331329790.png` });

  // Submit form
  console.log('Submitting bounty creation...');
  await page.locator('#create-bounty-btn').click();

  // Wait for redirect to details page
  await page.waitForURL(/\/bounties\//, { timeout: 10000 });
  const bountyUrl = page.url();
  console.log(`Created bounty successfully. Redirected to: ${bountyUrl}`);
  await page.waitForSelector('h1');
  await page.waitForTimeout(1500);

  console.log('--- Step 4: Authenticate as Worker (Bob) & Trigger Fee Confirmation Dialog ---');
  // Inject Worker (Bob) credentials to localStorage and reload details page
  await page.evaluate((creds) => {
    window.localStorage.setItem('algobounty_jwt', creds.jwt);
    window.localStorage.setItem('algobounty_address', creds.address);
    window.localStorage.setItem('algobounty_connected', 'true');
    window.localStorage.setItem('algobounty_wallet_type', 'pera');
  }, { jwt: worker.jwt, address: worker.address });

  // Reload the details page so Bob is logged in
  await page.reload();
  await page.waitForSelector('#claim-btn');
  await page.waitForTimeout(1000);

  // Click claim button to open the modal
  await page.locator('#claim-btn').click();
  await page.waitForSelector('#claim-modal-desc');
  await page.waitForTimeout(800); // Allow modal animation

  // Take screenshot of the real fee breakdown dialog
  await page.screenshot({ path: `${SCREENSHOT_DIR}/fee_breakdown_dialog_1784331338717.png` });
  console.log('E2E UX Simulation completed successfully. All screenshots captured.');
});
