import { test, expect } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

// Define screenshot paths
const CONV_ID = "02f516ab-7a8e-4da2-b688-922942ee50d2";
const BRAIN_DIR = `C:/Users/Garret/.gemini/antigravity/brain/${CONV_ID}`;
const DOCS_IMG_DIR = path.join(process.cwd(), '..', 'docs', 'images');

[BRAIN_DIR, DOCS_IMG_DIR].forEach(dir => {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
});

test('Run E2E UX Simulation for Alice Chen & Capture Main UI Screenshots', async ({ page }) => {
  page.on('console', msg => console.log('PAGE CONSOLE:', msg.text()));
  page.on('pageerror', err => console.log('PAGE ERROR:', err.message));

  // Load session tokens generated by wallet-factory
  const tokensPath = path.join(process.cwd(), 'session_tokens.json');
  let creator = { address: "CREATOR_ADDR_1234567890", jwt: "mock_jwt_creator" };
  let worker = { address: "WORKER_ADDR_1234567890", jwt: "mock_jwt_worker" };

  if (fs.existsSync(tokensPath) && fs.statSync(tokensPath).size > 10) {
    const tokens = JSON.parse(fs.readFileSync(tokensPath, 'utf-8'));
    if (tokens.CREATOR) creator = tokens.CREATOR;
    if (tokens.WORKER) worker = tokens.WORKER;
  }
  
  console.log('--- Step 1: Marketplace Dashboard View ---');
  await page.goto('http://localhost:3000/');
  await page.waitForTimeout(1000);
  await page.screenshot({ path: `${BRAIN_DIR}/marketplace_dashboard.png` });
  await page.screenshot({ path: `${DOCS_IMG_DIR}/marketplace_dashboard.png` });

  console.log('--- Step 2: Open Wallet Connection Modal ---');
  const walletBtn = page.locator('#wallet-connect-btn');
  if (await walletBtn.isVisible()) {
    await walletBtn.click();
    await page.waitForTimeout(500);
    await page.screenshot({ path: `${BRAIN_DIR}/wallet_modal.png` });
    await page.screenshot({ path: `${DOCS_IMG_DIR}/wallet_modal.png` });
    await page.mouse.click(10, 10);
    await page.waitForTimeout(300);
  }

  console.log('--- Step 3: Create Bounty Form View ---');
  await page.evaluate((creds) => {
    window.localStorage.setItem('algobounty_jwt', creds.jwt);
    window.localStorage.setItem('algobounty_address', creds.address);
    window.localStorage.setItem('algobounty_connected', 'true');
    window.localStorage.setItem('algobounty_wallet_type', 'pera');
  }, { jwt: creator.jwt, address: creator.address });

  await page.goto('http://localhost:3000/create');
  await page.waitForSelector('#description');

  await page.fill('#description', 'Build a Next.js Web3 Landing Page & Verification Hook');
  await page.fill('#amount', '150');
  await page.fill('#karma', '10');
  await page.fill('#repo-url', 'https://github.com/IcanBENCHurCAT/algo-bounty');
  await page.fill('#repo-labels', 'enhancement, UI');
  await page.fill('#tags', 'nextjs, wallet, algorand');
  
  const hitmToggle = page.locator('#hitm-toggle');
  if (await hitmToggle.isVisible()) {
    await hitmToggle.click();
    if (await page.locator('#hitm-days').isVisible()) {
      await page.fill('#hitm-days', '7');
    }
  }

  const taxCheckbox = page.locator('#tax-disclaimer-checkbox');
  if (await taxCheckbox.isVisible()) {
    await taxCheckbox.check();
  }

  await page.waitForTimeout(1000);
  await page.screenshot({ path: `${BRAIN_DIR}/create_bounty_form.png` });
  await page.screenshot({ path: `${DOCS_IMG_DIR}/create_bounty_form.png` });

  console.log('--- Step 4: Documentation Portal View ---');
  await page.goto('http://localhost:3000/docs');
  await page.waitForTimeout(1000);
  await page.screenshot({ path: `${BRAIN_DIR}/docs_portal_view.png` });
  await page.screenshot({ path: `${DOCS_IMG_DIR}/docs_portal_view.png` });

  console.log('E2E UX Simulation & Screenshot Capture finished successfully.');
});
